### ISSUE TITLE
Optimizing Entities with a Lucene index causes them to become unresponsive until you restart cottontail

### ISSUE THREAD

**Issue by silvanheller** [ppanopticon/cottontaildb#8]
To reproduce create an Entity with a text-index, optimize it, and run a query against it.

This doesn't have high priority because it's fixed by restarting Cottontail.

**Comment by silvanheller** [comment]
In the newest version, it's worse: You need to insert, restart cottontail, optimize and restart cottontail and then you can query. Without restarting between insert and optimization, the API call will run through but no actual optimization will take place.

**Comment by ppanopticon** [comment]
This should be fixed with the latest version on the master branch. Can you confirm?

**Comment by silvanheller** [comment]
Yes, works as expected.
